### ISSUE TITLE
Missing assets?

### ISSUE THREAD

**Issue by warrenalphonso** [SunTzunami/Transience_animation_PyArcade#1]
Thanks for publishing this cool demo! I cloned the repo but when running `Main_v2.1.py`, I get an error saying `feather.mp3` is missing. I commented out that line in the file to try to get it running without the music, and now I get an error saying `title/0.png` cannot be found. Are these files missing?

**Comment by SunTzunami** [comment]
Hi @warrenalphonso! I appreciate bringing the issue to my notice. I think I might've made an error while uploading the necessary files. Gimme some time. I'll add the missing files.

**Comment by SunTzunami** [comment]
@warrenalphonso I've added the necessary files. I cloned and ran it on my pc. and LGTM here Try running it now!

**Comment by SunTzunami** [comment]
@warrenalphonso Lemme know if it works. Thanks again for pointing out the error. Appreciate it. 👍🏾

**Comment by warrenalphonso** [comment]
Yup, it works. Awesome work!
